GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Programar con React y Node",
    "author": "Black",
    "url": "",
    "likes": 565
}